### PR TITLE
Eslint fixes

### PR DESCRIPTION
**Pull request by pi0neerpat**
This PR is an attempt to clean up all the 198 problems found when running eslint.

We can also discuss which rules we'd like to ignore, as there will inevitably be a few.

NOTE: In the meantime, add `--no-verify` at the end of your commit to skip the eslint pre-commit check.

### CODE REVIEW

**Comment by ejwessel** [comment]
How does this relate to what was merged here: https://github.com/Send-Tribute/tribute-rDAI/pull/35

**Comment by pi0neerpat** [comment]
It's not really relates. This is just to set up eslint and fix all the outstanding changes. No logic is changed and the frontend should remain unaffected. Formatting only

**Comment by pi0neerpat** [comment]
Relevant

https://twitter.com/cassidoo/status/1185656470953549824?s=20

**Comment by pi0neerpat** [comment]
Leaving out Tribute.js and Scanner.js as we may not be using those in the future.

**Pull request merged**
